version: '3.8'
services:

  #database
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: onionmap_db
      MYSQL_USER: onionmap_user
      MYSQL_PASSWORD: 123qwe
    ports:
      - '4306:3306'
    networks:
      - onionmap
    volumes:
      - ./dockerFiles/mysql/dbData:/var/lib/mysql

  #application
  php:
    container_name: php
    build:
      context: ./dockerFiles/php/
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/onionmap
    networks:
      - onionmap
    depends_on:
      - database

  #webserver
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/onionmap
      - ./dockerFiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - onionmap
    depends_on:
      - php
      - database
networks:
  onionmap: