# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Infrastructure\Framework\:
        resource: '../src/Infrastructure/Framework/*'
        exclude:
            - '../src/Infrastructure/Framework/{DependencyInjection,Kernel.php}'

    App\Core\Application\Contract\ICommandBus : '@App\Infrastructure\Framework\MessageBus\CommandBus'
    App\Core\Application\Contract\IEventBus : '@App\Infrastructure\Framework\MessageBus\EventBus'
    App\Core\Application\Contract\IQueryBus : '@App\Infrastructure\Framework\MessageBus\QueryBus'

    App\Core\Domain\Repository\ICompanyRepository : '@App\Infrastructure\Persistence\Doctrine\Repository\CompanyRepository'
    App\Core\Domain\Repository\IInvoiceRepository : '@App\Infrastructure\Persistence\Doctrine\Repository\InvoiceRepository'

    App\Core\Application\Event\Company\IDoSomething: '@App\Infrastructure\Notification\DoSomething'
    App\Core\Application\Event\Invoice\IDoSomething: '@App\Infrastructure\Notification\DoSomething'

    App\Presentation\:
        resource: '../src/Presentation/*'
    App\Core\Application\UseCase\:
        resource: '../src/Core/Application/UseCase'
    App\Core\Domain\Model\Entity\:
        resource: '../src/Core/Domain/Model/Entity'
    App\Core\Domain\Model\ValueObject\:
        resource: '../src/Core/Domain/Model/ValueObject'
    App\Core\Application\Command\:
        resource: '../src/Core/Application/Command'
        tags: [ { name: messenger.message_handler, bus: command.bus } ]
    App\Core\Application\Event\:
        resource: '../src/Core/Application/Event'
        tags: [ { name: messenger.message_handler, bus: event.bus } ]
    App\Core\Application\Query\:
        resource: '../src/Core/Application/Query'
        tags: [ { name: messenger.message_handler, bus: query.bus } ]
    App\Presentation\Api\Rest\Controller\:
        resource: '../src/Presentation/Api/Rest/Controller'
        tags: [ { name: controller.service_arguments } ]
    App\Infrastructure\Persistence\Doctrine\Repository\:
        resource: '../src/Infrastructure/Persistence/Doctrine/Repository'
        tags: [ { name: app.entity_repository } ]
    App\Infrastructure\Notification\DoSomething:
    # please note that last definitions always *replace* previous ones
