# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Core\Contract\ICommandBus : '@App\Infrastructure\CommandBus'
    App\Core\Contract\IEventBus : '@App\Infrastructure\EventBus'
    App\Core\Contract\IQueryBus : '@App\Infrastructure\QueryBus'
    App\Core\Application\Company\Command\:
        resource: '../src/Core/Application/Company/Command'
        tags: [ { name: messenger.message_handler, bus: command.bus } ]
    App\Core\Application\Company\Event\:
        resource: '../src/Core/Application/Company/Event'
        tags: [ { name: messenger.message_handler, bus: event.bus } ]
    App\Core\Application\Company\Query\:
        resource: '../src/Core/Application/Company/Query'
        tags: [ { name: messenger.message_handler, bus: query.bus } ]
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
